### ISSUE TITLE
Java heap space on .ints()

### ISSUE THREAD

**Issue by afxgroup** [grunka/fortuna#4]
Something like 

fortuna.ints(game.getNumbermin(), game.getNumbermax()).boxed().collect(Collectors.toList())

cause a Java Heap Space error

`	at java.util.Arrays.copyOf(Arrays.java:3181) ~[na:1.8.0_172]
	at java.util.ArrayList.grow(ArrayList.java:265) ~[na:1.8.0_172]
	at java.util.ArrayList.ensureExplicitCapacity(ArrayList.java:239) ~[na:1.8.0_172]
	at java.util.ArrayList.ensureCapacityInternal(ArrayList.java:231) ~[na:1.8.0_172]
	at java.util.ArrayList.add(ArrayList.java:462) ~[na:1.8.0_172]
	at java.util.stream.Collectors$$Lambda$26/830048777.accept(Unknown Source) ~[na:na]
	at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169) ~[na:1.8.0_172]
	at java.util.stream.IntPipeline$4$1.accept(IntPipeline.java:250) ~[na:1.8.0_172]
	at java.util.Random$RandomIntsSpliterator.forEachRemaining(Random.java:1044) ~[na:1.8.0_172]
	at java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:693) ~[na:1.8.0_172]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[na:1.8.0_172]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[na:1.8.0_172]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[na:1.8.0_172]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:1.8.0_172]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[na:1.8.0_172]`

**Comment by grunka** [comment]
Well that's not really a problem with the RNG unless I'm missing something. The code example tries to collect an infinite stream of integers into a list which will make the application run out of memory regardless of what produces the list of numbers. The `ints` function with three parameters creates a stream of a specific size.
